// TEMPORARY DATA



export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "201",
    name: "Aman Jangra",
    email: "amanjangra@mox.com",
    photo:
      "/myphoto.jpg",
    phone: "1234567890",
    subjects: [ "Physical Education"],
    classes: ["11B", "12A", "11C"],
    address: "123 Main St, Powerhouse, Rohtak",
  },
  {
    id: 2,
    teacherId: "202",
    name: "Prince Kaushik",
    email: "princeKaushik@mox.com",
    photo:
      "/myphoto.jpg",
    phone: "1234567890",
    subjects: ["Maths"],
    classes: ["8A", "10B", "9C"],
    address: "123 Main St, Sheetal nagar, Rphtak",
  },
  {
    id: 3,
    teacherId: "203",
    name: "Mahak Garg",
    email: "gargmahak25@mox.com",
    photo:
      "/myphoto.jpg",
    phone: "1234567890",
    subjects: ["Chemistry"],
    classes: ["11A", "12B"],
    address: "123 Main St, Janta Colony, Rohtak",
  },
  {
    id: 4,
    teacherId: "204",
    name: "Sunny jangra",
    email: "jangrasunny@gmail.com",
    photo:
      "/myphoto.jpg",
    phone: "1234567890",
    subjects: ["History"],
    classes: ["6A", "7B", "8C"],
    address: "123 Main St, , Rohtak",
  },
  {
    id: 5,
    teacherId: "205",
    name: "Anjali",
    email: "Anjali07@mox.com",
    photo:
      "/myphoto.jpg",
    phone: "1234567890",
    subjects: ["Music"],
    classes: ["11A", "12B", "11C"],
    address: "123 Main St, Omaxe City, Rohtak",
  },
  {
    id: 6,
    teacherId: "206",
    name: "Kajal Pawaria",
    email: "pawariakaju18@gmail.com",
    photo:
      "/myphoto.jpg",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["9A", "10B", "9C"],
    address: "123 Main St, Metro Station, Mundka",
  },
  {
    id: 7,
    teacherId: "207",
    name: "Himanshi Goyal",
    email: "HimanshiJangra207@mox.com",
    photo:
      "/myphoto.jpg",
    phone: "1234567890",
    subjects: ["English"],
    classes: ["10A", "9B", "11C"],
    address: "123 Main St, Kamla nagar, Rohtak",
  },
  {
    id: 8,
    teacherId: "208",
    name: "Dheeraj Pawaria",
    email: "Dheerajpawaria20@mox.com",
    photo:
      "/myphoto.jpg",
    phone: "1234567890",
    subjects: ["Geography",],
    classes: ["6A", "8B", "7C"],
    address: "123 Main St, D-Park, Rohtak",
  },
  {
    id: 9,
    teacherId: "209",
    name: "Onish Goyat",
    email: "goyatonish16@mox.com",
    photo:
      "/myphoto.jpg",
    phone: "1234567890",
    subjects: ["Hindi",],
    classes: ["5A", "4B", "3C"],
    address: "123 St, Sheetal nagar, Rohtak",
  },
  {
    id: 10,
    teacherId: "210",
    name: "Prince Lakra",
    email: "Princelakra17@mox.com",
    photo:
      "/myphoto.jpg",
    phone: "1234567890",
    subjects: ["Psychology"],
    classes: ["9A", "10B", "10C"],
    address: "123 Main St, Sec 3, Rohtak",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "01",
    name: "Rahul Jangra",
    email: "Rahuljangra@gmail.com",
    photo:
      "/myphoto.jpg",
    phone: "9812345673",
    grade: "A+",
    class: "11A",
    address: "123 Main St, Sheetal nagar, Rohtak",
  },
  {
    id: 2,
    studentId: "02",
    name: "Shiva Garg",
    email: "Shivagarg25@gmail.com",
    photo:
      "/myphoto.jpg",
    phone: "8684******",
    grade: "E",
    class: "11A",
    address: "123/34, Janta Colony, Rohtak",
  },
  {
    id: 3,
    studentId: "03",
    name: "Mayank Gupta",
    email: "MayankGupta@gmail.com",
    photo:
      "/myphoto.jpg",
    phone: "8595******",
    grade: "B",
    class: "11A",
    address: "123 Main St, Anytown, Rohtak",
  },
  {
    id: 4,
    studentId: "04",
    name: "Bhishek Kumar",
    email: "bhishek@gmail.com",
    photo:
      "/myphoto.jpg",
    phone: "8800******",
    grade: "B-",
    class: "11A",
    address: "K917, Mangolpuri, Delhi",
  },
  {
    id: 5,
    studentId: "05",
    name: "Naveen Hooda",
    email: "naveenhooda7@gmail.com",
    photo:
      "/myphoto.jpg",
    phone: "8816******",
    grade: "B+",
    class: "11A",
    address: "123 Main St, Vijay nagar, Rohtak",
  },
  {
    id: 6,
    studentId: "06",
    name: "Mohit Hooda",
    email: "mohithooda@gmail.com",
    photo:
      "/myphoto.jpg",
    phone: "9992******",
    grade: "C",
    class: "11A",
    address: "123 Main St, Ekta Colony, Rohtak",
  },
  {
    id: 7,
    studentId: "07",
    name: "Prashant Ahlawat",
    email: "ahlawatprashant@gmail.com",
    photo:
      "/myphoto.jpg",
    phone: "9996******",
    grade: "A+",
    class: "11A",
    address: "123 Main St, Ram gopal colony, Rohtak",
  },
  {
    id: 8,
    studentId: "08",
    name: "Sunny sinhmar",
    email: "sunny@gmail.com",
    photo:
      "/myphoto.jpg",
    phone: "8766******",
    grade: "A",
    class: "11A",
    address: "123 Main St, Ram gopal colony, Rohtak",
  },
  {
    id: 9,
    studentId: "09",
    name: "Mahak Garg",
    email: "gargmahak25@gmail.com",
    photo:
      "/myphoto.jpg",
    phone: "7988******",
    grade: "F",
    class: "L Kg",
    address: "123/34, Janta Colony, Rohtak",
  },
  {
    id: 10,
    studentId: "10",
    name: "Yuvraj bhardwaj",
    email: "YuviBhanu@gmail.com",
    photo:
      "/myphoto.jpg",
    phone: "9896******",
    grade: "A+",
    class: "11A",
    address: "123 Main St, Janta Colony, Rohtak",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Umesh Kumar",
    studentName: ["Prince Kaushik"],
    phone: "9734******",
    address: "123 Main St, Sheetal Nagar, Rohtak",
  },
  {
    id: 2,
    name: "Sat Pal",
    studentName: ["Prince Lakra"],
    phone: "8438******",
    address: "123 Main St, Mundka, Delhi",
  },
  {
    id: 3,
    name: "Anuradha",
    studentName: ["Mayank Gupta"],
    phone: "7865******",
    address: "123 Main St, meena bajaar, Delhi",
  },
  {
    id: 4,
    name: "Vijay pal",
    studentName: ["Aman ahlawat"],
    phone: "7988******",
    address: "123 Main St, Sheetal Nagar, Rohtak",
  },
  {
    id: 5,
    name: " Satender",
    studentName: ["Rahul jangra"],
    phone: "8443******",
    address: "123 Main St, Sheetal Nagar, Rohtak",
  },
  {
    id: 6,
    name: "Kuldeep Singh",
    studentName: ["Bhishek Kumar"],
    phone: "8800******",
    address: "K917, Mangolpuri, Delhi",
  },
  {
    id: 7,
    name: "Paami",
    studentName: ["Sifat Bindra"],
    phone: "9463******",
    address: "123 Main St, Anytown, Delhi",
  },
  {
    id: 7,
    name: "Rajbir Barak",
    studentName: ["Sahil Barak"],
    phone: "7404******",
    address: "1513/34, Sheetal Nagar, Rohtak",
  },
  
];

export const subjectsData = [
  {
    id: 201,
    subjectName: "Physical Education",
    teachers: ["Aman Jangra"],
  },
  {
    id: 202,
    subjectName: "Maths",
    teachers: ["Prince Kaushik"],
  },
  {
    id: 203,
    subjectName: "Chemistry",
    teachers: ["Mahak Garg"],
  },
  {
    id: 204,
    subjectName: "History",
    teachers: ["Sunny jangra"],
  },
  {
    id: 205,
    subjectName: "Music",
    teachers: ["Anjali"],
  },
  {
    id: 206,
    subjectName: "Biology",
    teachers: ["Kajal Pawaria"],
  },
  {
    id: 207,
    subjectName: "English",
    teachers: ["Himanshi Goyal"],
  },
  {
    id: 208,
    subjectName: "Geography",
    teachers: ["Dheeraj Pawaria"],
  },
  {
    id: 209,
    subjectName: "Hindi",
    teachers: ["Onish Goyat"],
  },
  {
    id: 210,
    subjectName: "Psychology",
    teachers: ["Prince Lakra"],
  },
];

export const classesData = [
  {
    id: 1,
    className: "1A",
    capacity: 45,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    className: "2B",
    capacity: 50,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    className: "3C",
    capacity: 48,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    className: "4B",
    capacity: 47,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    className: "5A",
    capacity: 44,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    className: "5B",
    capacity: 45,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    className: "7A",
    capacity: 51,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    className: "6B",
    capacity: 43,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    className: "6C",
    capacity: 56,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    className: "6D",
    capacity: 49,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Mahak Garg",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// Calendar data (date should me changed according to the current date)
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 0, 10, 8, 0),
    end: new Date(2025, 0, 10, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 0, 10, 9, 45),
    end: new Date(2025, 0, 10, 10, 30),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 0, 10, 11, 0),
    end: new Date(2025, 0, 10, 11, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 0, 10, 12, 15),
    end: new Date(2025, 0, 10, 13, 0),
  },
  {
  title: "History",
  allDay: false,
  start: new Date(2025, 0, 9, 14, 0),
  end: new Date(2025, 0, 9, 14, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 0, 12, 14, 0),
    end: new Date(2025, 0, 12, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 0, 13, 9, 0),
    end: new Date(2025, 0, 13, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 0, 13, 10, 0),
    end: new Date(2025, 0, 13, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 0, 13, 11, 0),
    end: new Date(2025, 0, 13, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2025, 0, 13, 14, 0),
    end: new Date(2025, 0, 13, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 0, 14, 8, 0),
    end: new Date(2025, 0, 14, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 0, 14, 10, 0),
    end: new Date(2025, 0, 14, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 0, 14, 13, 0),
    end: new Date(2025, 0, 14, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 0, 14, 14, 0),
    end: new Date(2025, 0, 14, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 0, 15, 9, 0),
    end: new Date(2025, 0, 15, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 0, 15, 10, 0),
    end: new Date(2025, 0, 15, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 0, 15, 11, 0),
    end: new Date(2025, 0, 15, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2025, 0, 15, 14, 0),
    end: new Date(2025, 0, 15, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 0, 16, 8, 0),
    end: new Date(2025, 0, 16, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 0, 16, 9, 0),
    end: new Date(2025, 0, 16, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 0, 16, 11, 0),
    end: new Date(2025, 0, 16, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 0, 16, 13, 0),
    end: new Date(2025, 0, 16, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 0, 16, 14, 0),
    end: new Date(2025, 0, 16, 14, 45),
  },
];